#!/bin/bash                                                                     
    sudo -H /usr/bin/easy_install pip                                                   
    sudo -H /usr/local/bin/pip install ansible                                          
    /usr/local/bin/ansible-playbook macsetup.yml
